name: wsk_angular
description: Web Starter Kit for Angular
version: 0.6.2
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-wsk-angular

dependencies:
  browser: any

  angular: ">=1.0.0 <2.0.0"

  validate: any

  wsk_material: ">=0.6.0 <0.7.0"
    #path: /Volumes/Daten/DevLocal/DevDart/WskMaterial

  logging: any
  logging_handlers: any
  console_log_handler: any
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

dev_dependencies:
  unittest: any

  # Angular braucht das!
  mock: ">=0.11.0+1 <0.12.0"

#------------------------------------------------
# Kann mit dart-ptransformers generiert werden.
#
transformers:
- angular:
    # dart_sdk:   "/Developer/dart-1.8.5/dart-sdk"

    # List is necessary because of this bug: http://goo.gl/4Rb3wr
    html_files: [
      'web/index.html',
      'web/views/animation.html',
      'web/views/button.html',
      'web/views/cards.html',
      'web/views/checkbox.html',
      'web/views/dropdown.html',
      'web/views/firstsub.html',
      'web/views/footer.html',
      'web/views/home.html',
      'web/views/icon-toggle.html',
      'web/views/item.html',
      'web/views/list.html',
      'web/views/pallet.html',
      'web/views/radio.html',
      'web/views/shadow.html',
      'web/views/spinner.html',
      'web/views/slider.html',
      'web/views/switch.html',
      'web/views/tabs.html',
      'web/views/textfield.html',
      'web/views/tooltip.html',
      'web/views/typography.html',
      'packages/wsk_angular/wsk_dialog/wsk_dialog.html'
      ]

- $dart2js:
    minify: false

