name: wsk_angular_layout_header_drawer_footer_sample
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  angular: ">=1.0.0 <2.0.0"

  wsk_angular:
    path: ../../


dev_dependencies:
  unittest: any

#------------------------------------------------
transformers:
- angular:
    # dart_sdk:   "/Developer/dart-1.8.5/dart-sdk"

    # List is necessary because of this bug: http://goo.gl/4Rb3wr
    html_files: [
      'web/index.html'
      ]

- $dart2js:
    minify: false
    sourceMaps: true


