name: wsk_angular_styleguide
description: Web Starter Kit for Angular - Styleguide
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-wsk-angular

dependencies:
  browser: any

  angular: ">=1.0.0 <2.0.0"

  wsk_angular:
    path: ../../

  prettify: any

dev_dependencies:
  unittest: any

#------------------------------------------------
# Kann mit dart-ptransformers generiert werden.
#

transformers:
- angular:
    # dart_sdk:   "/Developer/dart-1.8.5/dart-sdk"

    # List is necessary because of this bug: http://goo.gl/4Rb3wr
    html_files: [
      'web/index.html',

      'web/views/gettingstarted.html',

      'web/views/accordion.html',
      'web/views/animation.html',
      'web/views/button.html',
      'web/views/cards.html',
      'web/views/checkbox.html',
      'web/views/dialog.html',
      'web/views/draganddrop.html',
      'web/views/dropdown.html',
      'web/views/firstsub.html',
      'web/views/footer.html',
      'web/views/home.html',
      'web/views/icon-toggle.html',
      'web/views/item.html',
      'web/views/list.html',
      'web/views/pallet.html',
      'web/views/radio.html',
      'web/views/shadow.html',
      'web/views/spinner.html',
      'web/views/slider.html',
      'web/views/switch.html',
      'web/views/tabs.html',
      'web/views/textfield.html',
      'web/views/toast.html',
      'web/views/tooltip.html',
      'web/views/typography.html',

      'web/views/theming.html',

      'web/views/usage/toast.html'
      ]

- $dart2js:
    minify: false
    sourceMaps: true
